backstage-community-sessions/README.md

IDK if Lunar should be a link to our GH org or our main page lunar.app or it should be our @lunarway gh handle.
We can use this PR to set the standard for how details should be inserted 🙂

Add me as attendee

---

README.md

Open Mic is an event organized by Backstage users, we'll be hosting our first even at the end of the month. @OrkoHunter suggested we could add the event to this list of resources.
The other categories in the README use lists to reference different resources. However, "Meetups" used the list to showcase links about "Backstage Community Sessions." I took the route of making what existed into a kind of title, and adding Open Mic at the same level.
I did not replicate the structure of Backstage Community Sessions for Open Mic, and instead opted for a brief paragraph.

Adds Open Mic to meetups section

---

README.md

Various links from the last 3 months, including ThoughtWorks podcast, KubeCon talk, Prod Eng Silicon Valley panel discussion, Spotify Engineering blog posts, etc. (Some formatting tweaks, too.)
Signed-off-by: Jeff Feng <fengypants@gmail.com>

Added a backlog of links to posts, podcasts, talks

---

README.md

InfoWorld article comparing different approaches to FinOps features the Cost Insights plugin as one of the examples.

Adding link to InfoWorld article

---

README.md

It'll be easier for folks to find the relevant agenda issue from the README.

Add link to the next session in README

---

README.md

Added links to:
• American Airlines video demoing their Runway dev portal
• DAZN Engineering blog post on integrating Backstage
• FireHydrant blog post on building their official Backstage plugin

Adding links to blog posts and demos

---

README.md

The Open Mic has been replaced with an (approximately) quarterly Users
Unconference. 
I've also linked a few of the more important, recent Roadie
articles.

Updates from Roadie

---

README.md

Adding a few links, some older, some newer. Still trying to keep them in reverse chronological for the most part, which is why the Brex and QuintoAndar blog posts are where they are.
Added links to:
- NerdOut@Spotify podcast episodes
- American Airlines, Part 2 video
- Brex blog post
- QuintoAndar blog post

Adding blog post and podcasts

---

sigs/README.md
sigs/sig-catalog/README.md

Backstage and our fantastic community is growing larger every day and so does the desire to engage with fellow community members and find ways to contribute to the project. The Adopters and Contributors community sessions have helped a lot in this area but we want to have more focused conversations and introduce more ways for community members to get involved and contribute to Backstage.
That’s why we believe that it’s time to introduce Special Interest Groups (SIGs). The concept is nothing new and you might be familiar with them from the Kubernetes project which is largely organized around SIGs.
The idea behind a SIG is to gather community members with a special interest in a particular area of Backstage. The group will meet occasionally and discuss topics that fall under the scope of …

RFC: Introducing SIGs into the Backstage community

---

README.md

The Backstage newsletter from Spotify has migrated to a new distribution platform. So if you haven't signed up for it yet, here's a brand new, shiny link to get on the list.

Updated newsletter sign-up link

---

README.md

Added links to the Stack Overflow blog post, podcast episode, and webinar about Backstage.
Also moved the Rootly blog post up while I was in here, as the list of articles usually has most recent item at the top.

Added Stack Overflow links to README

---

README.md

Adding podcast recorded by getdx.com

Podcast: Implementing a developer portal - The Engineering Enablement Podcast - DX

---

project-areas/Maintainer-Guidance.md
project-areas/README.md
project-areas/core/README.md

This adds a new `project-areas` folder to this repo. At the root is a README with more information surrounding project areas, building upon the governance doc.
The main chunk of this PR is the new maintainer guidance doc, which describes common ways of working across project areas, as well a couple of different potential strategies for how to work within areas. You'll note that some of this is not reflected in reality, the plan is to fix that but also to agree on the way forward in this PR 😁 
I've also added an initial `project-areas/core` folder with a README that briefly describes some of the ways of working of the core maintainers. The idea is that each project area may have a folder at `project-areas/<name>` where any important information related to that area can be documented.
For …

Add new project areas section

---

README.md

Guy Menahem is a seasoned DevOps/Platform Engineer and a CNCF Ambassador, that recently started making content around Backstage and advocating for Platform Engineering. This YouTube series is excellent for any platform builder, from the very foundational principles of Platform Engineering leading up to a step-by-step tutorial to deploying Backstage "the hard way". 
This is one of the best tutorials out there IMO and should be featured here.

Add the "Platform Engineering & Backstage" YouTube Series 

---

README.md

Link leads to event from March 2022 and it seems there were no further editions. Description in the README says it's quarterly event

Added "inactive" note to Backstage Users Unconference

---

sigs/sig-adoption/README.md

Suggesting this due to low attendance and sparse discussion topics. I think there's a bit too much overlap with the new framework and adoption SIGs at this point. Figured we can keep the SIG organization, channel, and docs around for the time being, and organize meetings ad-hoc instead.

sigs/sig-adoption: pause recurring meetings

---

.github/ISSUE_TEMPLATE/org_member.yaml
GOVERNANCE.md

I propose the the following update to our governance in order to simplify the process for becoming an org member with write access (i.e. code ownership) in the community plugins repository.
We discussed the need for this update in today's community plugins SIG, but we've also been discussing something similar in the core maintainers team for a while too. Right now it's too hard to become an org member, to the point where it adds significant friction to both the contribution and maintenance of the community plugins. It's not spelled out plainly in the updated text, but this effectively makes the community plugins project area maintainers the gatekeepers for who can become an org member by being a plugin maintainer, since they approve those contributions.
The idea is that write access is …

GOVERNANCE.md: add path to become an org member as a plugin maintainer

---

backstage-community-sessions/README.md

Right now, we add a link to each Community Session agenda issue each month. Instead, propose linking to a filtered view of the relevant issues for past and upcoming sessions.
Also adding a link to the session recordings.

Updating links to Community Session agenda issues

---

GOVERNANCE.md

I realized that in the governance update in #151 I left a catch-22 in place by failing to update the "Becoming a Plugin Maintainer" section. This unwinds that to properly clarify that it is the responsibility of the community plugin area maintainers to first approve and merge changes to CODEOWNERS before plugin maintainer (and org member) status is granted.
👀 @backstage/maintainers @backstage/community-plugins-maintainers

Update GOVERNANCE.md to clarify path to plugin maintainer

---

sigs/sig-community-plugins/README.md

Currently, we have duplicate lists of members of Community Plugins SIG. Refer to the OWNERS file as the source of truth.
---- 
This is is out of sync as it is today, and I figure cross-referencing will prevent them getting out of sync in future.

reference OWNERS file in sig-community-plugins

---

sigs/README.md

Adding sig-docs to the list of SIGs in the main SIGs README.

doc: Adding sig-docs to the list of SIGs

---

.github/ISSUE_TEMPLATE/org_member.yaml

As discussed during the community plugins SIG, this PR adds a required checkbox to the organization membership request template to ensure that applicants have read the [Organization Member responsibilities](https://github.com/backstage/community/blob/master/GOVERNANCE.md#organization-member).
It also includes a note asking applicants to specifically review the [Plugin Maintainer section](https://github.com/backstage/community/blob/master/GOVERNANCE.md#plugin-maintainer) if they are applying through the third option.

add org membership responsibilities checkbox to org_member issue template

---

catalog-info.yaml

This was merged by mistake in https://github.com/backstage/community/pull/212.
Branch protection rules are now in place, but having a `catalog-info.yaml` kinda makes sense, just aligning it with https://github.com/backstage/backstage/blob/master/catalog-info.yaml

catalog-info.yaml: fix spec
