backstage-community-sessions/README.md
Closes #2 
Here is the recording of the session https://www.youtube.com/watch?v=4-VX9tDdJYY
You are welcome to review the PR or update the list as a follow-up PR.
=> Recording, minutes of meeting and list of attendees for the Feb 17 meetup

README.md
Link to a post on The New Stack about the Kubernetes plugin.
=> Added new article to list of blog posts

README.md
Adding a link to The Kubelist Podcast and the r/kuberenetes AMA.
=> Adding recent K8s AMA and podcast appearance

README.md
New InfoQ article on Golden Paths in Backstage
=> Add InfoQ article to blogs

README.md
https://snyk.io/blog/backstage-integration-with-the-snyk-api/
=> Add Snyk blog post

backstage-community-sessions/README.md
Closes https://github.com/backstage/community/issues/7
Here is the recording of the session - https://www.youtube.com/watch?v=rRphwXeq33Q
You are welcome to review the PR or update the list as a follow-up PR.
=> Add recording, notes and attendees of Mar 17 meetup

README.md
Article features Backstage as an example for reducing friction. Also added "Snyk Blog" as the source for the Snyk plugin post.
=> Added LeadDev article to blog list

README.md
Links to Backstage on ThoughtWorks' Tech Radar. Links to RedMonk article and videos.
=> Adding ThoughtWorks and RedMonk posts

backstage-community-sessions/README.md
https://github.com/backstage/community/issues/20
=> Add recording and notes from jun 16 meetup

README.md, backstage-community-sessions/README.md
Signed-off-by: Himanshu Mishra <himanshu@orkohunter.net>
=> Updates from July 21 meetup

README.md, backstage-community-sessions/README.md
Recording - https://www.youtube.com/watch?v=9_f7hMHAZqY
The next one is on September 15th https://github.com/backstage/community/issues/30
=> Updates from previous community session (Aug 2021)

README.md
We wrote a post about our adoption story and about all the features we contributed to Backstage in the last year. Happy reading!
=> Add a blog post from the SDA SE

README.md
We wrote a blog post that outlines how Backstage can improve the DX of Cloud native teams and proposes secrets management as an example :)
=> Adds a blog post from Frontside

README.md
Added a link to episode 04 of the NerdOut@Spotify podcast, featuring early adopters Netflix and American Airlines.
=> NerdOut@Spotify Ep.04: Backstage in the Wild

sigs/sig-catalog/README.md
Added the public link to the meeting notes for the Catalog SIG.
Signed-off-by: Francesco Corti <francescoc@spotify.com>
=> Added the public link to the meeting notes for the Catalog SIG.

sigs/sig-catalog/README.md
=> sig-catalog: update Discord link

README.md
So we know where it comes from
=> Added Rootly Source

README.md
With the creation of the new discord channel brazil I thought it would be cool to suggest the addition of some blogs in Portuguese that I participated in :)
=> Add some PT-BR Backstage Talks/Podcast/Blogs

sigs/README.md, sigs/sig-adoption/README.md
Adding the sig-adoption content.
Signed-off-by: Francesco Corti <francescoc@spotify.com>
=> Adding the sig-adoption content

README.md
Few Backstage related blog posts I've written
=> Add my blog posts

README.md
https://engineering.zalando.com/posts/2023/08/sunrise-zalandos-developer-platform-based-on-backstage.html
=> Added lessons learned post from Zalando

project-areas/permission-framework/README.md
=> Add permission framework project area and initial backlog skeleton

sigs/sig-adoption/README.md
Meeting link has been updated, so reflect that in this repo.
=> Update the SIG Adoption meeting link

README.md
https://medium.com/quintoandar-tech-blog/how-we-are-creating-a-knowledge-base-on-quintoandar-with-an-open-source-q-a-plugin-on-backstage-279faf4d6f61
=> Add blog about Q&A plugin

README.md
Hey Team! :wave: 
This adds a blog post about the permissions framework and how OPA can also integrate with it! Hope you like it!
Thanks!
=> Adding Backstage + OPA Blog Post

GOVERNANCE.md
Fix missing link to the CNCF Code of Conduct.
=> Fix broken link

sigs/README.md
Added link to sig-framework. Removed link to sig-catalog.
=> Update SIG README

sigs/sig-docs/README.md
Added the meeting notes and video call links
=> Updated Doc SIG Links

sigs/sig-adoption/README.md
This one was a while out of date
=> sigs/sig-adoption: update leadership

sigs/sig-docs/README.md
=> Updated SIG Docs day of week

project-areas/auditor/README.md
references https://github.com/backstage/backstage/pull/28721
=> doc: add auditor project area

GOVERNANCE.md
Adds the reviewer role to the governance model.
=> docs: add reviewer role
